### ISSUE TITLE
Aplicar Internacionalização nas telas do frontend

### ISSUE THREAD

**Issue by KahCosta** [Vamos-Parcelar-Lift-Learning/Frontend#43]
- [ ] Aplicar internacionalização nas demais telas, conforme aplicado na home da aplicação

**Comment by FabianaRibas** [comment]
Feita a Internacionalização da tela de Login

**Comment by FabianaRibas** [comment]
Feita internacionalização da pagina de comprovante (detalhes)

**Comment by mateusroriz** [comment]
Feita a Internacionalização da pagina de lista de comprovante

**Comment by mateusroriz** [comment]
Feita Internacionalização da pagina de consulta de débitos
